server:
  port: 8085

spring:
  application: 
    name: zuul-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  healthcheck: 
    enabled: true
zuul:
  routes:
    user-database: 
      url: http://localhost:8081
    user-service:
      url: http://localhost:8082
    bookmark-database:
      url: http://localhost:8083